### ISSUE TITLE
Instruction in tutorial to prepend /vsicurl/ before your pasted in URL is not accepted in QGIS 3.26.2 and does not work

### ISSUE THREAD

**Issue by pworrall** [cogeotiff/www.cogeo.org#60]
I've attempted several ways to get the "Build Virtual Raster" tool in QGIS to build a .vrt file using actual virtual files (https:...).  It works fine with the same files if I previously download them, but I get the error "Incorrect parameter value for INPUT" when I try to access them on the web.  I've tried accessing the files both with and without the /vsiurl/ prepend, and I ger the same error.  The Python code below I copied from the tool dialog, then I edited it and ran it in the Python Console.  Any guidance would be greatly appreciated!

processing.run("gdal:buildvirtualraster", {'INPUT':[' /vsicurl/https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/1m/Projects/IN_Indiana_Statewide_LiDAR_2017_B17/TIFF/USGS_1M_16_x65y432_IN_Indiana_Statewide_LiDAR_2017_B17.tif',' /vsicurl/https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/1m/Projects/IN_Indiana_Statewide_LiDAR_2017_B17/TIFF/USGS_1M_16_x64y436_IN_Indiana_Statewide_LiDAR_2017_B17.tif'],'RESOLUTION':0,'SEPARATE':False,'PROJ_DIFFERENCE':False,'ADD_ALPHA':False,'ASSIGN_CRS':None,'RESAMPLING':0,'SRC_NODATA':'','EXTRA':'','OUTPUT':'TEMPORARY_OUTPUT'})

Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\tools\general.py", line 108, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\core\Processing.py", line 181, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: Unable to execute algorithm
**Incorrect parameter value for INPUT**

**Comment by batugane** [comment]
Hi there @pworrall,

I wanted to check if the problem is still persistent. I followed the guide at [QGIS Training Manual on Data Manipulation](https://docs.qgis.org/3.34/en/docs/training_manual/rasters/data_manipulation.html) and used the exact same data from the following URLs:

- [https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/1m/Projects/IN_Indiana_Statewide_LiDAR_2017_B17/TIFF/](https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/1m/Projects/IN_Indiana_Statewide_LiDAR_2017_B17/TIFF/)
- [https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/1m/Projects/IN_Indiana_Statewide_LiDAR_2017_B17/TIFF/USGS_1M_16_x65y432_IN_Indiana_Statewide_LiDAR_2017_B17.tif](https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/1m/Projects/IN_Indiana_Statewide_LiDAR_2017_B17/TIFF/USGS_1M_16_x65y432_IN_Indiana_Statewide_LiDAR_2017_B17.tif)

Here is the GDAL output:

- **QGIS version:** 3.36.1-Maidenhead
- **QGIS code revision:** 3e589453
- **Qt version:** 5.15.3
- **Python version:** 3.9.18
- **GDAL version:** 3.8.4
- **GEOS version:** 3.12.1-CAPI-1.18.1
- **PROJ version:** Rel. 9.3.1, December 1st, 2023
- **PDAL version:** 2.6.0 (git-version: 3fced5)

Algorithm started at: 2024-05-28T13:53:35

Algorithm 'Build virtual raster' starting…
Input parameters:
{ 'ADD_ALPHA' : False, 'ASSIGN_CRS' : None, 'EXTRA' : '', 'INPUT' : ['/vsicurl/https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/1m/Projects/IN_Indiana_Statewide_LiDAR_2017_B17/TIFF/USGS_1M_16_x64y436_IN_Indiana_Statewide_LiDAR_2017_B17.tif','/vsicurl/https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/1m/Projects/IN_Indiana_Statewide_LiDAR_2017_B17/TIFF/USGS_1M_16_x65y432_IN_Indiana_Statewide_LiDAR_2017_B17.tif'], 'OUTPUT' : 'TEMPORARY_OUTPUT', 'PROJ_DIFFERENCE' : False, 'RESAMPLING' : 0, 'RESOLUTION' : 0, 'SEPARATE' : False, 'SRC_NODATA' : '' }

GDAL command output:
```
0...10...20...30...40...50...60...70...80...90...100 - done.
Process completed successfully
Execution completed in 6.63 seconds
Results:
  OUTPUT: C:/****/processing_wnPrXZ/161d25745d1c49de808b6c44d88d7b88/OUTPUT.vrt
```

Loading resulting layers
**Algorithm 'Build virtual raster' finished as you can see there are no errors and the algorithm finished successfully.**

Let me know if this helps or if you still encounter any issues.

Best regards,
Batuhan

**Comment by pworrall** [comment]
Thanks for the Feedback - I'll try it again!
